Fixes #1846 by displaying a user-friendly error message instead of a stack trace on boot error
jenkinsci/configuration-as-code-plugin pull request #2199
Opened 2023-01-29 03:36 UTC by lakshmishreea122003

Fixes issue(https://github.com/jenkinsci/configuration-as-code-plugin/issues/1846) with configurator exception being thrown for unknown keys. Now logs the unknown keys and throws a more informative exception.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [X ] Ensure that the pull request title represents the desired changelog entry
- [ X] Please describe what you did
- [X ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

2023-01-31 15:40 UTC, krisstern commented on plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
> +
Try removing the trailing spaces at L732.

2023-01-31 15:48 UTC, krisstern commented on plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
> +
```suggestion
```

2023-02-07 14:21 UTC, timja requested changes
this will still show the stacktrace from what I can see.

2023-02-11 14:26 UTC, lakshmishreea122003 commented
Sorry for the late response due to my exams. I felt code snippet in this PR provides a more user-friendly error message compared to the current code snippet, as it throws a ConfiguratorException with a message "Invalid Configuration. Please check your configuration and try again." that can be displayed and by logging the message in the sever level the stack trace would not be shown . If my assumption was wrong, please can you give me a clue as to how I can go ahead to work this issue in a better manner.

2023-02-11 22:23 UTC, timja commented
It's not the message itself that's the problem its the stacktrace.

The Jenkins core boot failure error message should have the option of suppressing the stacktrace, to fix this issue you would likely need to see where that error page is built in [Jenkins core](https://github.com/jenkinsci/jenkins) and make displaying the stacktrace optional in some way.

2023-02-12 02:43 UTC, lakshmishreea122003 commented
I shall start working on this issue as per your advice.

2024-11-02 09:07 UTC, timja commented
This was solved separately

2024-11-02 09:07 UTC, closed without merging